# Generated by Django 4.2.9 on 2024-01-31 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ShaalaaMiner', '0016_remove_question_solution_solution_question_and_more'),
        ('core', '0011_alter_metaattributeextra_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_marks', models.IntegerField(choices=[(20, '20 Marks'), (40, '40 Marks')])),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.board')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('meta', models.CharField(max_length=255)),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assessment.questionpaper')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShaalaaMiner.question')),
            ],
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(through='Assessment.QuestionPaperQuestion', to='ShaalaaMiner.question'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
    ]
