# Generated by Django 4.2.9 on 2024-02-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='max_marks',
            field=models.IntegerField(),
        ),
    ]
