# Generated by Django 4.2.9 on 2024-02-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0002_alter_questionpaper_max_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaperquestion',
            name='question_paper',
        ),
        migrations.RemoveField(
            model_name='questionpaperquestion',
            name='questions',
        ),
        migrations.DeleteModel(
            name='QuestionPaper',
        ),
        migrations.DeleteModel(
            name='QuestionPaperQuestion',
        ),
    ]
