# Generated by Django 4.2.9 on 2024-02-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0006_questionpaperquestionrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(through='Assessment.QuestionPaperQuestionRelation', to='Assessment.questionpaperquestion'),
        ),
    ]
