# Generated by Django 4.2.9 on 2024-02-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0008_rename_questionpaper_questionpaperquestionrelation_question_paper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaperquestionrelation',
            name='marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
