# Generated by Django 4.2.9 on 2024-02-02 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_grade_to_scrape'),
        ('Assessment', '0009_questionpaperquestionrelation_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(through='Assessment.QuestionPaperQuestionRelation', to='core.question'),
        ),
        migrations.AlterField(
            model_name='questionpaperquestionrelation',
            name='question_paper_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question'),
        ),
    ]
