# Generated by Django 4.2.9 on 2024-02-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0011_delete_questionpaperquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpaperquestionrelation',
            old_name='question_paper_question',
            new_name='question',
        ),
    ]
