# Generated by Django 4.2.9 on 2024-02-02 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_grade_to_scrape'),
        ('Assessment', '0012_rename_question_paper_question_questionpaperquestionrelation_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaperFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionPaperFormatQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_head', models.CharField(max_length=255)),
                ('question_paper_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assessment.questionpaperformat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionPaperFormatQuestionSubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_paper_format_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assessment.questionpaperformatquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
