# Generated by Django 4.2.9 on 2024-02-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_grade_to_scrape'),
        ('Assessment', '0013_questionpaperformat_questionpaperformatquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaperformatquestionsubquestion',
            name='question_type',
            field=models.ManyToManyField(to='core.questiontype'),
        ),
    ]
