# Generated by Django 4.2.9 on 2024-02-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0015_questionpaperformatquestionsubquestion_max_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaperformatquestionsubquestion',
            name='question_type',
        ),
    ]
