# Generated by Django 4.2.9 on 2024-02-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_publication_site'),
        ('Assessment', '0018_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaperformat',
            name='question_type',
        ),
        migrations.AddField(
            model_name='questionpaperformat',
            name='question_type',
            field=models.ManyToManyField(blank=True, null=True, to='core.questiontype'),
        ),
    ]
