# Generated by Django 4.2.9 on 2024-02-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_publication_site'),
        ('Assessment', '0020_alter_questionpaperformat_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaperformat',
            name='question_type',
            field=models.ManyToManyField(blank=True, limit_choices_to={'depth': 1}, null=True, to='core.questiontype'),
        ),
    ]
