# Generated by Django 4.2.9 on 2024-01-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_to_scrape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='site',
            field=models.IntegerField(choices=[(1, 'EBalbharti'), (2, 'shaalaa')]),
        ),
    ]
