# Generated by Django 4.2.9 on 2024-01-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_spider_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=255)),
                ('attribute_value', models.BooleanField()),
                ('attribute_extra', models.CharField(max_length=255)),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.spider')),
            ],
        ),
    ]
