# Generated by Django 4.2.9 on 2024-01-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='attribute_extra',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
