# Generated by Django 4.2.9 on 2024-01-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_spider_url_alter_meta_attribute_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spider',
            old_name='site',
            new_name='site_name',
        ),
        migrations.AddField(
            model_name='spider',
            name='spider_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
