# Generated by Django 4.2.9 on 2024-01-24 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_metaattributeextra_attribute_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='attribute_extras',
        ),
        migrations.AddField(
            model_name='meta',
            name='attribute_extra',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='metaattributeextra',
            name='meta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.meta'),
            preserve_default=False,
        ),
    ]
