# Generated by Django 4.2.9 on 2024-01-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_meta_attribute_extras_meta_attribute_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaattributeextra',
            name='attribute_extra_value',
            field=models.TextField(),
        ),
    ]
