# Generated by Django 4.2.9 on 2024-01-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_metaattributeextra_attribute_extra_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaattributeextra',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_extras', to='core.meta'),
        ),
    ]
