# Generated by Django 4.2.9 on 2024-02-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_chapter_question_questiontype_solution_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publication',
            unique_together=set(),
        ),
    ]
