# Generated by Django 4.2.9 on 2024-02-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_questionsubtype_question_type_subtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type_subtype',
            new_name='subtype',
        ),
    ]
