# Generated by Django 4.2.9 on 2024-02-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_question_type_questiontype_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontype',
            old_name='parent',
            new_name='child',
        ),
    ]
