# Generated by Django 4.2.9 on 2024-02-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_questiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.questiontype'),
        ),
    ]
