# Generated by Django 4.2.9 on 2024-02-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_subject_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='site',
            field=models.CharField(default='ShaalaaSpider', max_length=255),
        ),
    ]
