# Generated by Django 4.2.9 on 2024-02-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_solution_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
