# Generated by Django 4.2.9 on 2024-03-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_question_core_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='note',
            field=models.CharField(blank=True, max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
