# Generated by Django 4.2.9 on 2024-01-25 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShaalaaMiner', '0005_questionresource_questiontype_solutionresource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='resource',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ShaalaaMiner.questionresource'),
        ),
        migrations.AlterField(
            model_name='question',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='resource',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ShaalaaMiner.questionresource'),
        ),
    ]
