# Generated by Django 4.2.9 on 2024-01-25 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShaalaaMiner', '0006_alter_question_resource_alter_question_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='resource',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ShaalaaMiner.solutionresource'),
        ),
    ]
