# Generated by Django 4.2.9 on 2024-01-25 07:46

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ShaalaaMiner', '0011_alter_question_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='solutionresource',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShaalaaMiner.solution'),
        ),
    ]
