# Generated by Django 4.2.9 on 2024-01-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShaalaaMiner', '0013_remove_solutionresource_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='solution',
        ),
    ]
