# Generated by Django 4.2.9 on 2024-02-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0003_remove_questionpaperquestion_question_paper_and_more'),
        ('ShaalaaMiner', '0016_remove_question_solution_solution_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.RemoveField(
            model_name='questionresource',
            name='question',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='question',
        ),
        migrations.RemoveField(
            model_name='solutionresource',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='publication',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionResource',
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.DeleteModel(
            name='SolutionResource',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
