# Generated by Django 4.2.9 on 2024-02-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpaperquestion',
            old_name='questions',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='questionpaperquestion',
            name='question_paper',
        ),
        migrations.DeleteModel(
            name='QuestionPaperQuestionRelation',
        ),
    ]
