# Generated by Django 4.2.9 on 2024-02-02 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0005_rename_questions_questionpaperquestion_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaperQuestionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', models.CharField(blank=True, max_length=555, null=True)),
                ('order', models.IntegerField()),
                ('questionpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assessment.questionpaper')),
                ('questionpaperquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assessment.questionpaperquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
