# Generated by Django 4.2.9 on 2024-02-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0010_alter_questionpaper_questions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionPaperQuestion',
        ),
    ]
