# Generated by Django 4.2.9 on 2024-02-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0014_questionpaperformatquestionsubquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaperformatquestionsubquestion',
            name='max_marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
