# Generated by Django 4.2.9 on 2024-02-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0016_remove_questionpaperformatquestionsubquestion_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaperformat',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='questionpaperformat',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='questionpaperformatquestion',
            name='question_paper_format',
        ),
        migrations.RemoveField(
            model_name='questionpaperformatquestionsubquestion',
            name='question_paper_format_question',
        ),
        migrations.RemoveField(
            model_name='questionpaperquestionrelation',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionpaperquestionrelation',
            name='question_paper',
        ),
        migrations.DeleteModel(
            name='QuestionPaper',
        ),
        migrations.DeleteModel(
            name='QuestionPaperFormat',
        ),
        migrations.DeleteModel(
            name='QuestionPaperFormatQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionPaperFormatQuestionSubQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionPaperQuestionRelation',
        ),
    ]
