# Generated by Django 4.2.9 on 2024-02-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0029_alter_publication_site'),
        ('Assessment', '0017_remove_questionpaperformat_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaperFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('node_type', models.IntegerField(choices=[(1, 'FORMAT_ID'), (2, 'QUESTION_SUBQUESTION'), (3, 'TYPE')])),
                ('marks', models.IntegerField()),
                ('data', models.CharField(max_length=155)),
                ('question_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.questiontype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionPaperFormatIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assessment.questionpaperformat')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
    ]
