# Generated by Django 4.2.9 on 2024-03-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_question_custom_question_note_question_visibility'),
        ('Assessment', '0024_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='chapters',
        ),
        migrations.AddField(
            model_name='assessment',
            name='chapters',
            field=models.ManyToManyField(blank=True, null=True, to='core.chapter'),
        ),
    ]
