# Generated by Django 4.2.9 on 2025-04-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_question_custom_question_note_question_visibility'),
        ('Assessment', '0026_alter_assessment_chapters_alter_assessment_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='assessment', to='core.question'),
        ),
    ]
