# Generated by Django 4.2.9 on 2024-01-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShaalaaMiner', '0003_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaalaa_id', models.IntegerField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('descriptive_name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('to_scrape', models.BooleanField(default=False)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShaalaaMiner.grade')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShaalaaMiner.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('to_scrape', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShaalaaMiner.subject')),
            ],
        ),
    ]
