# Generated by Django 4.2.9 on 2025-04-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
