# Generated by Django 4.2.9 on 2024-01-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_site_spider_site_name_spider_spider_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAttributeExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_extra', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='meta',
            name='attribute_extra',
        ),
        migrations.AddField(
            model_name='meta',
            name='attribute_user_meata',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meta',
            name='attribute_extras',
            field=models.ManyToManyField(to='core.metaattributeextra'),
        ),
    ]
