# Generated by Django 4.2.9 on 2024-01-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_metaattributeextra_remove_meta_attribute_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaattributeextra',
            name='attribute_extra',
        ),
        migrations.AddField(
            model_name='metaattributeextra',
            name='attribute_extra_name',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metaattributeextra',
            name='attribute_extra_value',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meta',
            name='attribute_extras',
            field=models.ManyToManyField(blank=True, to='core.metaattributeextra'),
        ),
    ]
