# Generated by Django 4.2.9 on 2024-02-03 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_grade_to_scrape'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_sub_type', models.CharField(max_length=255)),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questiontype')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='type_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.questionsubtype'),
        ),
    ]
