# Generated by Django 4.2.9 on 2024-02-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_parent_questiontype_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontype',
            old_name='child',
            new_name='parent',
        ),
    ]
