# Generated by Django 4.2.9 on 2024-02-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_questiontype_depth_questiontype_numchild_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontype',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='path',
        ),
    ]
