# Generated by Django 4.2.9 on 2024-02-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assessment', '0016_remove_questionpaperformatquestionsubquestion_question_type'),
        ('core', '0023_remove_questiontype_depth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ]
