# Generated by Django 4.2.9 on 2024-02-06 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.publication'),
        ),
    ]
