# Generated by Django 4.2.9 on 2024-02-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_publication_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
