# Generated by Django 4.2.9 on 2024-02-08 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_publication_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.questiontype'),
        ),
    ]
